import { ChakraProvider, VStack } from '@chakra-ui/react'
import Head from 'next/head'
import LightMode from '~/components/nav/LightMode'
import Nav from '~/components/nav/Nav'
import { theme } from '~/styles/theme'
import '../styles/globals.css'
import '/styles/Home.module.css'

function MyApp({ Component, pageProps }) {
	return (
		<ChakraProvider theme={theme}>
			<Head>
				<title>Brain Storm</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<VStack as='main' alignItems='stretch' flex={1} spacing='0'>
				<Nav />
				<LightMode />

				<Component {...pageProps} />
			</VStack>
		</ChakraProvider>
	)
}

export default MyApp
