import {
	Box,
	Text,
	useColorMode,
	useColorModeValue,
	Image,
	VStack,
	HStack,
	Heading,
} from '@chakra-ui/react'
import { DragControls, isDragActive, motion, transform } from 'framer-motion'
import Head from 'next/head'

import { BsFillLightbulbOffFill, BsLightbulbFill } from 'react-icons/bs'
import Appear from '~/components/animate/Appear'
import Flicker from '~/components/animate/Flicker'
import Pulse from '~/components/animate/Pulse'
import Nav from '~/components/nav/Nav'

export default function Home() {
	const { colorMode, toggleColorMode } = useColorMode()
	const mode = useColorModeValue(<BsFillLightbulbOffFill />, <BsLightbulbFill />)

	return (
		<div>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Nav />
			<VStack h={'85vh'} justifyContent={'center'}>
				<motion.div
					initial={{ rotate: 0 }}
					whileTap={{ scale: 1.05, rotate: [0, 5, -5, 5, 0] }}
				>
					<motion.div
						initial={{ opacity: 0 }}
						whileInView={{
							opacity: [1, 0.99, 1],
							scale: [1, 1.05, 1],
							left: [0, 0.1, 1, 0.2, 1, 0],
							right: [0, 0.2, 1, 0.3, 1, 0],
						}}
						transition={{ ease: 'easeInOut', repeat: 'Infinity', duration: 10 }}
					>
						<Box>
							<Image h={{ sm: 600 }} src={'/brainStorm/tvBrain.png'} />
						</Box>
					</motion.div>
				</motion.div>

				<HStack spacing={8} pt={4}>
					<motion.div
						initial={{ opacity: 0 }}
						whileInView={{
							opacity: [1, 0.5, 1, 0.5, 1],
							scale: [1, 1.05, 1],
						}}
						whileHover={{ opacity: [1, 0.5, 1, 0.5, 1] }}
					>
						<Heading fontSize={'3xl'} textAlign={'center'} fontFamily={'Rubik Glitch'}>
							Creative.
						</Heading>
					</motion.div>
					<motion.div
						initial={{ opacity: 0 }}
						whileInView={{
							opacity: [1, 0.5, 1, 0.5, 1],
							scale: [1, 1.05, 1],
						}}
						whileHover={{ opacity: [1, 0.5, 1, 0.5, 1] }}
					>
						<Heading fontSize={'3xl'} textAlign={'center'} fontFamily={'Rubik Glitch'}>
							Intuative.
						</Heading>
					</motion.div>
					<motion.div
						initial={{ opacity: 0 }}
						whileInView={{
							opacity: [1, 0.5, 1, 0.5, 1],
							scale: [1, 1.05, 1],
						}}
						whileHover={{ opacity: [1, 0.5, 1, 0.5, 1] }}
					>
						<Heading fontSize={'3xl'} textAlign={'center'} fontFamily={'Rubik Glitch'}>
							Design
						</Heading>
					</motion.div>
				</HStack>
			</VStack>

			<Box position={'fixed'} bottom={0} left={2} cursor={'pointer'}>
				<motion.div
					whileHover={{ scale: 1.4 }}
					transition={{ duration: 0.3, ease: 'easeInOut' }}
				>
					<Text
						py={4}
						onClick={toggleColorMode}
						_light={{ color: 'white', _hover: { color: 'pink.500' } }}
						_dark={{ color: 'pink.500' }}
					>
						{mode}
					</Text>
				</motion.div>
			</Box>
		</div>
	)
}
