import {
	Box,
	Heading,
	HStack,
	Icon,
	Image,
	Spacer,
	Stack,
	Text,
	useColorModeValue,
	VStack,
} from '@chakra-ui/react'
import Head from 'next/head'
import { SlGhost } from 'react-icons/sl'
import {
	GiErlenmeyer,
	GiBleedingEye,
	GiAnglerFish,
	GiBubbles,
	GiSpottedBug,
	GiExecutionerHood,
} from 'react-icons/gi'

import MyLink from '~/components/MyLink'
import { CgSmileNoMouth } from 'react-icons/cg'
import { RiEyeCloseLine, RiBugFill } from 'react-icons/ri'
import Nav from '~/components/refact/Nav'
import { motion } from 'framer-motion'
export default function Home() {
	const bigFont = {
		fontSize: { sm: '9xl', base: '5xl' },
		fontWeight: '900',
	}
	const HannahFont = {
		fontSize: { sm: '8xl', base: '5xl' },
		fontWeight: '900',
		px: { sm: '4' },
	}
	const iconProps = {
		fontSize: { base: '3xl', sm: '8xl' },
	}

	return (
		<VStack
			flex={'1'}
			spacing={'0'}
			alignItems={'stretch'}
			justify={{ sm: 'center' }}
			py={{ base: '4', sm: 0 }}
		>
			<Head>
				<title>Home</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<HStack justify={'center'}>
				<Heading fontFamily={'Gloria Hallelujah'} {...bigFont}>
					Hell
				</Heading>

				<motion.div
					animate={{
						rotate: [0, 10, -20, 0],
					}}
					transition={{ duration: 10, repeat: Infinity, ease: 'easeInOut' }}
				>
					<Icon {...iconProps} as={useColorModeValue(GiErlenmeyer, SlGhost)} />{' '}
				</motion.div>
				<Heading fontFamily={'Gloria Hallelujah'} {...bigFont}>
					W
				</Heading>
				<motion.div
					animate={{
						rotate: [0, 30, -30, 90, -90, 360, 0],
						// color: ['#36CB6A', '#AF36CB', '#367DCB', '#F2D80A'],
					}}
					transition={{ duration: 60, repeat: Infinity, ease: 'easeInOut' }}
				>
					<Icon {...iconProps} as={useColorModeValue(GiBubbles, CgSmileNoMouth)} />
				</motion.div>
				<Heading fontFamily={'Gloria Hallelujah'} {...bigFont}>
					rld
				</Heading>
			</HStack>
			<HStack alignItems={'stretch'} justify={'center'}>
				<Text fontFamily={'Poppins'} {...HannahFont}>
					I am
				</Text>

				<Text fontFamily={'Poppins'} {...HannahFont}>
					Hannah;
				</Text>
			</HStack>
			<Stack
				direction={['column', 'row']}
				spacing={{ base: '0' }}
				justify={'center'}
				align={'center'}
			>
				<Text Text fontFamily={'Rubik Microbe '} fontSize={{ base: '7xl', sm: '6xl' }}>
					Artist,
				</Text>
				<Text fontFamily={'Rubik Gemstones'} fontSize={{ base: '3xl', sm: '6xl' }}>
					Insect Enthusiast,
				</Text>
			</Stack>

			<Stack
				direction={['column', 'row']}
				justify={'center'}
				spacing={{ base: '0', sm: 4 }}
				align={'center'}
			>
				<Text fontFamily={'Gloria Hallelujah'} {...bigFont}>
					Dev.
				</Text>
				<VStack spacing={{ base: '0' }} justify={'center'}>
					<Text
						fontFamily={'Reenie Beanie'}
						{...bigFont}
						fontSize={{ base: '4xl', sm: '5xl' }}
					>
						Take a look
					</Text>
					<Text
						fontFamily={'Reenie Beanie'}
						{...bigFont}
						fontSize={{ base: '4xl', sm: '5xl' }}
					>
						at my work
					</Text>

					<Icon as={useColorModeValue(RiEyeCloseLine, GiBleedingEye)} fontSize={'5xl'} />
				</VStack>
			</Stack>
		</VStack>
	)
}
